const js = require('@eslint/js');
const prettier = require('eslint-config-prettier/flat');

const globals = {
  window: 'readonly',
  document: 'readonly',
  console: 'readonly',
  require: 'readonly',
  module: 'readonly',
  exports: 'readonly',
  global: 'readonly',
  process: 'readonly',
  Buffer: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  setImmediate: 'readonly',
  clearImmediate: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  requestIdleCallback: 'readonly',
  performance: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  navigator: 'readonly',
  Image: 'readonly',
  Blob: 'readonly',
  URL: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  Node: 'readonly',
  HTMLElement: 'readonly',
  MutationObserver: 'readonly',
  feather: 'readonly',
  Notyf: 'readonly',
  showToast: 'readonly',
  createDragImage: 'readonly'
};

module.exports = [
  {
    ignores: [
      'node_modules/',
      'dist/',
      'build/',
      'release/',
      'coverage/'
    ]
  },
  js.configs.recommended,
  prettier,
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals
    },
    rules: {
      'no-debugger': 'error',
      'no-new-func': 'error',
      'no-implied-eval': 'error',
      'no-loop-func': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-var': 'error',

      camelcase: ['warn', { properties: 'never' }],
      indent: ['warn', 2],
      quotes: ['warn', 'single'],
      semi: ['warn', 'always'],
      radix: 'warn',
      yoda: 'warn',
      'array-bracket-spacing': ['warn', 'never'],
      'arrow-spacing': 'warn',
      'block-spacing': 'warn',
      'brace-style': ['warn', '1tbs', { allowSingleLine: true }],
      'comma-dangle': ['warn', 'never'],
      'comma-spacing': 'warn',
      'computed-property-spacing': ['warn', 'never'],
      'eol-last': 'warn',
      'func-call-spacing': ['warn', 'never'],
      'keyword-spacing': 'warn',
      'linebreak-style': ['warn', 'unix'],
      'new-cap': 'warn',
      'new-parens': 'warn',
      'no-array-constructor': 'warn',
      'no-console': 'warn',
      'no-else-return': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-empty-function': 'warn',
      'no-implicit-coercion': 'warn',
      'no-implicit-globals': 'warn',
      'no-invalid-this': 'warn',
      'no-magic-numbers': ['warn', { ignore: [0, 1, 2, 10, 100, 1000] }],
      'no-multi-spaces': 'warn',
      'no-multiple-empty-lines': ['warn', { max: 2, maxEOF: 1 }],
      'no-new': 'warn',
      'no-new-object': 'warn',
      'no-new-wrappers': 'warn',
      'no-return-assign': 'warn',
      'no-return-await': 'warn',
      'no-throw-literal': 'warn',
      'no-trailing-spaces': 'warn',
      'no-unused-expressions': 'warn',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-useless-call': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-escape': 'warn',
      'no-useless-return': 'warn',
      'no-void': 'warn',
      'no-warning-comments': 'warn',
      'object-curly-spacing': ['warn', 'always'],
      'object-shorthand': 'warn',
      'prefer-const': 'warn',
      'prefer-promise-reject-errors': 'warn',
      'prefer-template': 'warn',
      'require-await': 'warn',
      'space-before-blocks': 'warn',
      'space-before-function-paren': ['warn', 'always'],
      'space-infix-ops': 'warn',
      'template-curly-spacing': ['warn', 'never'],
      'vars-on-top': 'warn',
      'wrap-iife': 'warn'
    }
  }
];
